const courses = [
  {
    title: "HTML Fundamentals",
    slug: "html-fundamentals",
    technology: "html",
    description: "Learn the building blocks of the web with semantic HTML5, forms, accessibility, and modern markup practices.",
    level: "beginner",
    duration: "6 hours",
    price: 7,
    lessons: 24,
    thumbnail: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg",
    includes: [
      "24 hands-on lessons",
      "5 hands-on projects",
      "Quizzes after each module",
      "Private GitHub repository with starter and solution code",
      "Downloadable cheat sheets",
      "Certificate of completion",
    ],
    isPublished: true,
  },
  {
    title: "CSS Mastery",
    slug: "css-mastery",
    technology: "css",
    description: "Master layouts with Flexbox and Grid, responsive design, animations, and modern CSS architecture.",
    level: "beginner",
    duration: "10 hours",
    price: 9,
    lessons: 32,
    thumbnail: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg",
    includes: [
      "32 hands-on lessons",
      "8 responsive layout projects",
      "Flexbox and Grid deep dives",
      "Private GitHub repository with all project files",
      "Design system templates",
      "Certificate of completion",
    ],
    isPublished: true,
  },
  {
    title: "JavaScript Complete",
    slug: "javascript-complete",
    technology: "javascript",
    description: "From variables and functions to async programming, DOM manipulation, and ES6+ features for real-world apps.",
    level: "intermediate",
    duration: "18 hours",
    price: 13,
    lessons: 48,
    thumbnail: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
    includes: [
      "48 hands-on lessons",
      "12 coding challenges",
      "6 mini apps and 2 capstone projects",
      "Private GitHub repository with full source code",
      "API integration exercises",
      "Certificate of completion",
    ],
    isPublished: true,
  },
  {
    title: "React Development",
    slug: "react-development",
    technology: "react",
    description: "Build modern UIs with React hooks, state management, routing, and production-ready component patterns.",
    level: "intermediate",
    duration: "22 hours",
    price: 16,
    lessons: 56,
    thumbnail: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
    includes: [
      "56 hands-on lessons",
      "Build 4 full React applications",
      "Hooks, Context, and React Router",
      "Private GitHub repository with monorepo project structure",
      "Deployment guides for Vercel and Netlify",
      "Certificate of completion",
    ],
    isPublished: true,
  },
  {
    title: "Python Programming",
    slug: "python-programming",
    technology: "python",
    description: "Learn Python from scratch covering syntax, OOP, file handling, APIs, and building backend applications.",
    level: "beginner",
    duration: "20 hours",
    price: 11,
    lessons: 52,
    thumbnail: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg",
    includes: [
      "52 hands-on lessons",
      "10 Python scripts and 3 full projects",
      "OOP and data structures modules",
      "Private GitHub repository with exercises and solutions",
      "Flask intro bonus module",
      "Certificate of completion",
    ],
    isPublished: true,
  },
  {
    title: "Node.js Backend Development",
    slug: "nodejs-backend-development",
    technology: "nodejs",
    description: "Build scalable backend services with Node.js, Express, REST APIs, authentication, and database integration.",
    level: "intermediate",
    duration: "20 hours",
    price: 15,
    lessons: 50,
    thumbnail: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
    includes: [
      "50 hands-on lessons",
      "Build 3 REST APIs from scratch",
      "JWT authentication and middleware patterns",
      "Private GitHub repository with full backend source code",
      "PM2 and VPS deployment guide",
      "Certificate of completion",
    ],
    isPublished: true,
  },
  {
    title: "C Programming",
    slug: "c-programming",
    technology: "c",
    description: "Understand core programming concepts with C, covering pointers, memory management, data structures, and system-level thinking.",
    level: "beginner",
    duration: "16 hours",
    price: 10,
    lessons: 40,
    thumbnail: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-original.svg",
    includes: [
      "40 hands-on lessons",
      "Pointers and memory management deep dive",
      "8 practice programs and 2 mini projects",
      "Private GitHub repository with exercises and solutions",
      "Data structures fundamentals module",
      "Certificate of completion",
    ],
    isPublished: true,
  },
  {
    title: "SQL for Developers",
    slug: "sql-for-developers",
    technology: "sql",
    description: "Master relational databases with SQL queries, joins, indexing, normalization, and real-world schema design.",
    level: "beginner",
    duration: "12 hours",
    price: 9,
    lessons: 30,
    thumbnail: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg",
    includes: [
      "30 hands-on lessons",
      "Real-world database schema projects",
      "Joins, subqueries, and indexing modules",
      "Private GitHub repository with sample databases",
      "Query optimization cheat sheets",
      "Certificate of completion",
    ],
    isPublished: true,
  },
  {
    title: "MongoDB & Database Design",
    slug: "mongodb-database-design",
    technology: "mongodb",
    description: "Design and work with NoSQL databases using MongoDB, covering schemas, aggregation, indexing, and Mongoose.",
    level: "intermediate",
    duration: "15 hours",
    price: 12,
    lessons: 34,
    thumbnail: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",    includes: [
      "34 hands-on lessons",
      "Schema design and aggregation pipeline projects",
      "Mongoose ODM deep dive",
      "Private GitHub repository with sample datasets",
      "Indexing and performance tuning module",
      "Certificate of completion",
    ],
    isPublished: true,
  },
];

module.exports = courses;