const courses = [
  {
    title: "HTML Fundamentals",
    slug: "html-fundamentals",
    technology: "html",
    description: "Learn the building blocks of the web with semantic HTML5, forms, accessibility, and modern markup practices.",
    level: "beginner",
    duration: "6 hours",
    price: 29,
    lessons: 24,
    thumbnail: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg",
    includes: [
      "24 video lessons",
      "5 hands-on projects",
      "Quizzes after each module",
      "Private GitHub repository with starter and solution code",
      "Downloadable cheat sheets",
      "Certificate of completion",
    ],
    githubRepo: "https://github.com/learncode/html-fundamentals-course",
    isPublished: true,
  },
  {
    title: "CSS Mastery",
    slug: "css-mastery",
    technology: "css",
    description: "Master layouts with Flexbox and Grid, responsive design, animations, and modern CSS architecture.",
    level: "beginner",
    duration: "10 hours",
    price: 39,
    lessons: 32,
    thumbnail: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg",
    includes: [
      "32 video lessons",
      "8 responsive layout projects",
      "Flexbox and Grid deep dives",
      "Private GitHub repository with all project files",
      "Design system templates",
      "Certificate of completion",
    ],
    githubRepo: "https://github.com/learncode/css-mastery-course",
    isPublished: true,
  },
  {
    title: "JavaScript Complete",
    slug: "javascript-complete",
    technology: "javascript",
    description: "From variables and functions to async programming, DOM manipulation, and ES6+ features for real-world apps.",
    level: "intermediate",
    duration: "18 hours",
    price: 49,
    lessons: 48,
    thumbnail: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
    includes: [
      "48 video lessons",
      "12 coding challenges",
      "6 mini apps and 2 capstone projects",
      "Private GitHub repository with full source code",
      "API integration exercises",
      "Certificate of completion",
    ],
    githubRepo: "https://github.com/learncode/javascript-complete-course",
    isPublished: true,
  },
  {
    title: "React Development",
    slug: "react-development",
    technology: "react",
    description: "Build modern UIs with React hooks, state management, routing, and production-ready component patterns.",
    level: "intermediate",
    duration: "22 hours",
    price: 59,
    lessons: 56,
    thumbnail: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
    includes: [
      "56 video lessons",
      "Build 4 full React applications",
      "Hooks, Context, and React Router",
      "Private GitHub repository with monorepo project structure",
      "Deployment guides for Vercel and Netlify",
      "Certificate of completion",
    ],
    githubRepo: "https://github.com/learncode/react-development-course",
    isPublished: true,
  },
  {
    title: "Python Programming",
    slug: "python-programming",
    technology: "python",
    description: "Learn Python from scratch covering syntax, OOP, file handling, APIs, and building backend applications.",
    level: "beginner",
    duration: "20 hours",
    price: 49,
    lessons: 52,
    thumbnail: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg",
    includes: [
      "52 video lessons",
      "10 Python scripts and 3 full projects",
      "OOP and data structures modules",
      "Private GitHub repository with exercises and solutions",
      "Flask intro bonus module",
      "Certificate of completion",
    ],
    githubRepo: "https://github.com/learncode/python-programming-course",
    isPublished: true,
  },
];

module.exports = courses;
